import arabic_reshaper
from bidi.algorithm import get_display

words={'chair':['seat',
'chairwoman',
'chairperson',
'chairman',
'bench',
'couch',
'wheelchair',
'professorship',
'recliner',
'president',
'ottoman',
'furniture',
'lead',
'stool',
'highchair',
'desk',
'electric chair',
'lawn chair',
'swivel chair',
'head',
'bar stool',
'sofa',
'rocking chair',
'armchair',
'chaise longue',
'straight chair',
'leg',
'office',
'side chair',
'sit',
'post',
'moderate',
'daybed',
'sitting'], 'bed':['bunk',
'mattress',
'bunk bed',
'hammock',
'bedroom',
'pillow',
'sleep',
'couch',
'headboard',
'murphy bed',
'furniture',
'blanket',
'make out',
'cot',
'bedstead',
'duvet',
'trundle bed',
'bottom',
'mattresses',
'set',
'stratum',
'bedchamber',
'sickbed',
'gold',
'seedbed'
]}

for word in words:
    related_words=words[word]
    reshaped_bidi_related_words=get_display(arabic_reshaper.reshape(words[word]))
    print(reshaped_bidi_related_words)